document.writeln("<PRE>")
document.write("<B> <font size=15>")
document.writeln("Halo Selamat datang")
document.write("</B> </font>")
document.write("<i>")
document.write("Document ini teks nya miring")
document.write("</i>")

document.write("<center>")
document.write("<hr height=600 color=black>")
document.writeln("<H1>UNIVERSITAS KOMPUTER INDONESIA</H1>")
document.writeln("<H2>FAKULTAS TEKNIK dan ILMU KOMPUTER<H2>")
document.writeln("<H3>JURUSAN TEKNIK INFORMATIKA<H3>")
document.write("Haloooooooo")
document.write("</center>")
